version: "3"
services:
  frontend:
    build: frontend/
    container_name: frontend
    ports:
      - 80:80
    networks: 
    - epam
  backend:
    build: lib_catalog/
    container_name: backend
    ports:
      - 8000:8000
    networks:
    - epam
    - backend
    depends_on:
    - postgres
  postgres:
    image: postgres:alpine3.14
    container_name: pgsql
    environment:
      POSTGRES_DB: "backend"
      POSTGRES_USER: "backend"
      POSTGRES_PASSWORD: "backend"
      POSTGRES_HOST: "0.0.0.0"
    networks:
    - backend
    volumes:
      - ../volumes/postgres/:/var/lib/postgresql/data/
networks:
  epam:
    driver: bridge
  backend:
    driver: bridge
volumes:
    backend_pgsql:
